import {
  StandardExerciseProps,
  StandardMealProps,
  StandardIngredientProps,
} from "../interfaces/GlobalInterface";

export const DUMMYEXERCISES: StandardExerciseProps[] = [
  {
    id: 1,
    Exercise: "Jogging",
    ExerciseData: { Miles: 3, Minutes: 3, Sets: 1 },
  },
  { id: 2, Exercise: "Pushups", ExerciseData: { Reps: 20, Sets: 2 } },
  { id: 3, Exercise: "Planks", ExerciseData: { Minutes: 2, Sets: 2 } },
  {
    id: 4,
    Exercise: "Dumbells",
    ExerciseData: { Reps: 10, Weight: 30, Sets: 2 },
  },
];

export const DUMMYMEALS: StandardMealProps[] = [
  {
    Meal: "Chicken Breast",
    Ingredients: [
      {
        Ingredient: "Chicken Breast",
        Calories: 200,
        Protein: 60,
        Sodium: 20,
        Cholesterol: 10,
        Sugar: 0,
        Carbs: 5,
      },
      {
        Ingredient: "Black Pepper",
        Calories: 5,
        Protein: 0,
        Sodium: 0,
        Cholesterol: 0,
        Sugar: 0,
        Carbs: 10,
      },
    ],
    MealData: {
      Calories: 5,
      Protein: 0,
      Sodium: 0,
      Cholesterol: 0,
      Sugar: 0,
      Carbs: 10,
    },
  },
  {
    Meal: "Hamburger",
    Ingredients: [
      {
        Ingredient: "Beef Patty",
        Calories: 200,
        Protein: 60,
        Sodium: 20,
        Cholesterol: 10,
        Sugar: 0,
        Carbs: 10,
      },
      {
        Ingredient: "Black Pepper",
        Calories: 5,
        Protein: 0,
        Sodium: 0,
        Cholesterol: 0,
        Sugar: 0,
        Carbs: 10,
      },
      {
        Ingredient: "Cheese",
        Calories: 5,
        Protein: 10,
        Sodium: 0,
        Cholesterol: 0,
        Sugar: 0,
        Carbs: 10,
      },
      {
        Ingredient: "Bun",
        Calories: 5,
        Protein: 0,
        Sodium: 0,
        Cholesterol: 0,
        Sugar: 0,
        Carbs: 10,
      },
    ],
    MealData: {
      Calories: 5,
      Protein: 0,
      Sodium: 0,
      Cholesterol: 0,
      Sugar: 0,
      Carbs: 10,
    },
  },
  {
    Meal: "Omelete",
    Ingredients: [
      {
        Ingredient: "Eggs",
        Calories: 200,
        Protein: 60,
        Sodium: 20,
        Cholesterol: 10,
        Sugar: 0,
        Carbs: 10,
      },
      {
        Ingredient: "Black Pepper",
        Calories: 5,
        Protein: 0,
        Sodium: 0,
        Cholesterol: 0,
        Sugar: 0,
        Carbs: 5,
      },
      {
        Ingredient: "Cheese",
        Calories: 5,
        Protein: 0,
        Sodium: 0,
        Cholesterol: 0,
        Sugar: 0,
        Carbs: 5,
      },
    ],
    MealData: {
      Calories: 5,
      Protein: 0,
      Sodium: 0,
      Cholesterol: 0,
      Sugar: 0,
      Carbs: 10,
    },
  },
  {
    Meal: "Greek Yogurt - Plain",
    Ingredients: [
      {
        Ingredient: "Greek Yogurt - Plain",
        Calories: 200,
        Protein: 60,
        Sodium: 20,
        Cholesterol: 10,
        Sugar: 0,
        Carbs: 3,
      },
    ],
    MealData: {
      Calories: 5,
      Protein: 0,
      Sodium: 0,
      Cholesterol: 0,
      Sugar: 0,
      Carbs: 10,
    },
  },
  {
    Meal: "Chicken Breast",
    Ingredients: [
      {
        Ingredient: "Chicken Breast",
        Calories: 200,
        Protein: 60,
        Sodium: 20,
        Cholesterol: 10,
        Sugar: 0,
        Carbs: 10,
      },
      {
        Ingredient: "Black Pepper",
        Calories: 5,
        Protein: 0,
        Sodium: 0,
        Cholesterol: 0,
        Sugar: 0,
        Carbs: 7,
      },
    ],
    MealData: {
      Calories: 5,
      Protein: 0,
      Sodium: 0,
      Cholesterol: 0,
      Sugar: 0,
      Carbs: 10,
    },
  },
];
