import { ProgramDetailsInterface } from "../../Components/Interfaces/ProgramDetailsInterface";

export const DUMMYMANAGE: ProgramDetailsInterface[] = [
    { 
      day: "Day 1",
      mealArray: [
        {
          time: "Breakfast",
          Meal: "Chicken",
          Calories: 200,
          Protein: 50,
          Fat: 10,
          Servings: 1,
          ServingSize: 3,
          Sodium: 15,
          Cholesterol: 20,
        },
        {
          time: "Breakfast",
          Meal: "Chicken",
          Calories: 200,
          Protein: 50,
          Fat: 10,
          Servings: 1,
          ServingSize: 3,
          Sodium: 15,
          Cholesterol: 20,
        },
        {
          time: "Breakfast",
          Meal: "Chicken",
          Calories: 200,
          Protein: 50,
          Fat: 10,
          Servings: 1,
          ServingSize: 3,
          Sodium: 15,
          Cholesterol: 20,
        },
        {
          time: "Breakfast",
          Meal: "Chicken",
          Calories: 200,
          Protein: 50,
          Fat: 10,
          Servings: 1,
          ServingSize: 3,
          Sodium: 15,
          Cholesterol: 20,
        },
        {
          time: "Breakfast",
          Meal: "Chicken",
          Calories: 200,
          Protein: 50,
          Fat: 10,
          Servings: 1,
          ServingSize: 3,
          Sodium: 15,
          Cholesterol: 20,
        },
      ],
      exerciseArray: [
        { Exercise: "Jogging", Miles: 2 },
        { Exercise: "Pushups", Reps: 20 },
        { Exercise: "Planks", Minutes: 2 },
        { Exercise: "Curls", Reps: 12, Sets: 2, Weight: 20 },
      ],
    },
    {
      day: "Day 2",
      mealArray: [
        {
          time: "Breakfast",
          Meal: "Chicken",
          Calories: 200,
          Protein: 50,
          Fat: 10,
          Servings: 1,
          ServingSize: 3,
          Sodium: 15,
          Cholesterol: 20,
        },
        {
          time: "Breakfast",
          Meal: "Chicken",
          Calories: 200,
          Protein: 50,
          Fat: 10,
          Servings: 1,
          ServingSize: 3,
          Sodium: 15,
          Cholesterol: 20,
        },
        {
          time: "Breakfast",
          Meal: "Chicken",
          Calories: 200,
          Protein: 50,
          Fat: 10,
          Servings: 1,
          ServingSize: 3,
          Sodium: 15,
          Cholesterol: 20,
        },
        {
          time: "Breakfast",
          Meal: "Chicken",
          Calories: 200,
          Protein: 50,
          Fat: 10,
          Servings: 1,
          ServingSize: 3,
          Sodium: 15,
          Cholesterol: 20,
        },
        {
          time: "Breakfast",
          Meal: "Chicken",
          Calories: 200,
          Protein: 50,
          Fat: 10,
          Servings: 1,
          ServingSize: 3,
          Sodium: 15,
          Cholesterol: 20,
        },
      ],
      exerciseArray: [
        { Exercise: "Jogging", Miles: 2 },
        { Exercise: "Pushups", Reps: 20 },
        { Exercise: "Planks", Minutes: 2 },
        { Exercise: "Curls", Reps: 12, Sets: 2, Weight: 20 },
      ],
    },
    {
      day: "Day 3",
      mealArray: [
        {
          time: "Breakfast",
          Meal: "Chicken",
          Calories: 200,
          Protein: 50,
          Fat: 10,
          Servings: 1,
          ServingSize: 3,
          Sodium: 15,
          Cholesterol: 20,
        },
        {
          time: "Breakfast",
          Meal: "Chicken",
          Calories: 200,
          Protein: 50,
          Fat: 10,
          Servings: 1,
          ServingSize: 3,
          Sodium: 15,
          Cholesterol: 20,
        },
        {
          time: "Breakfast",
          Meal: "Chicken",
          Calories: 200,
          Protein: 50,
          Fat: 10,
          Servings: 1,
          ServingSize: 3,
          Sodium: 15,
          Cholesterol: 20,
        },
        {
          time: "Breakfast",
          Meal: "Chicken",
          Calories: 200,
          Protein: 50,
          Fat: 10,
          Servings: 1,
          ServingSize: 3,
          Sodium: 15,
          Cholesterol: 20,
        },
        {
          time: "Breakfast",
          Meal: "Chicken",
          Calories: 200,
          Protein: 50,
          Fat: 10,
          Servings: 1,
          ServingSize: 3,
          Sodium: 15,
          Cholesterol: 20,
        },
      ],
      exerciseArray: [
        { Exercise: "Jogging", Miles: 2 },
        { Exercise: "Pushups", Reps: 20 },
        { Exercise: "Planks", Minutes: 2 },
        { Exercise: "Curls", Reps: 12, Sets: 2, Weight: 20 },
      ],
    },
    {
      day: "Day 4",
      mealArray: [
        {
          time: "Breakfast",
          Meal: "Chicken",
          Calories: 200,
          Protein: 50,
          Fat: 10,
          Servings: 1,
          ServingSize: 3,
          Sodium: 15,
          Cholesterol: 20,
        },
        {
          time: "Breakfast",
          Meal: "Chicken",
          Calories: 200,
          Protein: 50,
          Fat: 10,
          Servings: 1,
          ServingSize: 3,
          Sodium: 15,
          Cholesterol: 20,
        },
        {
          time: "Breakfast",
          Meal: "Chicken",
          Calories: 200,
          Protein: 50,
          Fat: 10,
          Servings: 1,
          ServingSize: 3,
          Sodium: 15,
          Cholesterol: 20,
        },
        {
          time: "Breakfast",
          Meal: "Chicken",
          Calories: 200,
          Protein: 50,
          Fat: 10,
          Servings: 1,
          ServingSize: 3,
          Sodium: 15,
          Cholesterol: 20,
        },
        {
          time: "Breakfast",
          Meal: "Chicken",
          Calories: 200,
          Protein: 50,
          Fat: 10,
          Servings: 1,
          ServingSize: 3,
          Sodium: 15,
          Cholesterol: 20,
        },
      ],
      exerciseArray: [
        { Exercise: "Jogging", Miles: 2 },
        { Exercise: "Pushups", Reps: 20 },
        { Exercise: "Planks", Minutes: 2 },
        { Exercise: "Curls", Reps: 12, Sets: 2, Weight: 20 },
      ],
    },
    {
      day: "Day 5",
      mealArray: [
        {
          time: "Breakfast",
          Meal: "Chicken",
          Calories: 200,
          Protein: 50,
          Fat: 10,
          Servings: 1,
          ServingSize: 3,
          Sodium: 15,
          Cholesterol: 20,
        },
        {
          time: "Breakfast",
          Meal: "Chicken",
          Calories: 200,
          Protein: 50,
          Fat: 10,
          Servings: 1,
          ServingSize: 3,
          Sodium: 15,
          Cholesterol: 20,
        },
        {
          time: "Breakfast",
          Meal: "Chicken",
          Calories: 200,
          Protein: 50,
          Fat: 10,
          Servings: 1,
          ServingSize: 3,
          Sodium: 15,
          Cholesterol: 20,
        },
        {
          time: "Breakfast",
          Meal: "Chicken",
          Calories: 200,
          Protein: 50,
          Fat: 10,
          Servings: 1,
          ServingSize: 3,
          Sodium: 15,
          Cholesterol: 20,
        },
        {
          time: "Breakfast",
          Meal: "Chicken",
          Calories: 200,
          Protein: 50,
          Fat: 10,
          Servings: 1,
          ServingSize: 3,
          Sodium: 15,
          Cholesterol: 20,
        },
      ],
      exerciseArray: [
        { Exercise: "Jogging", Miles: 2 },
        { Exercise: "Pushups", Reps: 20 },
        { Exercise: "Planks", Minutes: 2 },
        { Exercise: "Curls", Reps: 12, Sets: 2, Weight: 20 },
      ],
    },
  ];